### ISSUE TITLE
TypeError with Python 3.4.2

### ISSUE THREAD

**Issue by BonkaBonka** [mgood/jprops#12]
```
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jprops
>>> jprops.load_properties('server.props')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jamesc/build/wake/lib/python3.4/site-packages/jprops.py", line 27, in load_properties
    return mapping(iter_properties(fh))
  File "/home/jamesc/build/wake/lib/python3.4/site-packages/jprops.py", line 101, in iter_properties
    for line in _property_lines(fh):
  File "/home/jamesc/build/wake/lib/python3.4/site-packages/jprops.py", line 255, in _property_lines
    for line in _universal_newlines(fp):
  File "/home/jamesc/build/wake/lib/python3.4/site-packages/jprops.py", line 248, in _universal_newlines
    line = line.replace(b'\r\n', b'\n').replace(b'\r', b'\n')
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by mgood** [comment]
Instead of passing a filename to `load_properties()` you need to open the file, and pass the file object. There are several examples of the usage in the docs: http://mgood.github.io/jprops/

**Comment by BonkaBonka** [comment]
Oops, minimized the test case too much.  Wrapping the load_properties with the usual "with open(blah) as x" clause throws the same error, FWIW.

**Comment by mgood** [comment]
Oh ok, it looks like the docs need updated for Python 3. You'll need to use `open(filename, 'rb')` to open the file in binary mode (or use the mode `'wb'` to open for writing). jprops expects the raw bytes in order to decode them in the way described for the `.properties` format.

I'll reopen to include documentation on this.

**Comment by reinaldo13** [comment]
Added the aforementioned Python 3 info to the docs. Pending PR https://github.com/mgood/jprops/pull/16 approval.

**Comment by mgood** [comment]
Thanks for the docs PR.
