### ISSUE TITLE
Failure while writing comment when none provided

### ISSUE THREAD

**Issue by agautam-hs** [mgood/jprops#17]
Using all defaults, the following fails with python 3.5 (on Mac):

```python
        with open(client_props_file, 'w') as fp:
            jprops.store_properties(fp, client_props)
```

Error:

```
Traceback (most recent call last):
  File "/Users/agautam/tmp/00_PythonTest/scrap_process_file_from_luis.py", line 42, in <module>
    jprops.store_properties(fp, client_props)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jprops.py", line 43, in store_properties
    write_comment(fh, time.strftime('%a %b %d %H:%M:%S %Z %Y'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jprops.py", line 63, in write_comment
    fh.write(_escape_comment(comment))
TypeError: write() argument must be str, not bytes

```

**Comment by mgood** [comment]
When you're opening the file, use the mode `'wb'` instead to open it in binary mode. This is necessary since jprops handles the byte encoding itself.

There is a section about this in the [docs](http://mgood.github.io/jprops/) though maybe it could be moved into the README or something to make it more visible:

> Important notes for Python 3
> jprops expects bytes when decoding the property file, so with Python 3 you'll need to use  open(filename, 'rb') to open the property file in binary mode (or use the mode 'wb' to open for writing)

**Comment by agautam-hs** [comment]
I was following instructions from http://mgood.github.io/jprops/ - Though, didn't scroll down enough to see the note about Python 3.

Thanks for the quick response.

Ajay
