### ISSUE TITLE
jprops in conda forge

### ISSUE THREAD

**Issue by maartenbreddels** [mgood/jprops#18]
Hi, great package! I'm using it in my [vaex](https://github.com/maartenbreddels/vaex) package as a dependency, and I want to but it in the conda-forge channel. However, then also jprops needs to be in that channel, are you interested in doing that yourself, would really appreciate it 👍 .

**Comment by mgood** [comment]
Thanks! I'm not using this package now, so I don't really have time to maintain it, but you're welcome to post it to Conda if you like.
