### ISSUE TITLE
Preserving comments after parsing

### ISSUE THREAD

**Issue by elazarl** [mgood/jprops#6]
I'd like that

```
with open('a.properties', 'r') as f:
    p = jprops.load_properties(f)
with open('a.properties', 'w') as f:
    jprops.store_properties(f)
```

would be able to preserve comments. Maybe with a special 'props_dict' object mapping?

**Comment by jleclanche** [comment]
@mgood FYI, I wrote a parser which retains comments if you are interested:

https://github.com/translate/python-jproperties

**Comment by mgood** [comment]
@jleclanche thanks for sharing your parser. I'm not using the jprops library myself lately, so I don't think I'll get around to adding comment support. The way you're storing properties and comments makes sense, though you might want to take a closer look at the jprops parser, which I believe supports some features that yours doesn't. I included support for all the documented escape sequences and unicode encoding, which I don't see in your implementation.

**Comment by mgood** [comment]
After thinking about this some more, I went ahead and made a few changes in 6f7e87fe67d to allow parsing comments as well. You can get the comments by using `iter_properties()` and checking if the key is the sentinel value `jprops.COMMENT`:

```python
for key, value in jprops.iter_properties(fp, comments=True):
  if key is jprops.COMMENT:
    # handle comment
  else:
    # handle property
```

I haven't included a specialized data structure at this time, but that could be built on top of this change.

**Comment by jleclanche** [comment]
@mgood Unicode escapes are supported through python's decoder (in escape()/unescape()).

**Comment by mgood** [comment]
@jleclanche yeah, I did see that you had added the `unicode_escape` encoding. That's a clever use of the Python encoder, although Python's syntax does differ slightly from Java's. While I think that would handle decoding Java's syntax, Python includes some other escape sequences which may differ when encoding.

For example, it will encode some characters with the `\x` escape which I do not believe is valid in Java:

```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> u'\u0000'.encode('unicode_escape')
'\\x00'
```

With the jprops code I have tried hard to precisely implement all of the [Java properties file documentation](http://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#load(java.io.Reader)). There are a number of test cases included to check the behavior as thoroughly as I could.

Are there other features missing in jprops that you'd like to see? I'd be glad to discuss other enhancements.

**Comment by jleclanche** [comment]
Good point. I'll be implementing better parsing of backslash escapes though, seeing as invalid backslash sequences should be dropped. So `\x` should never appear by the time it reaches the python decoder.

**Comment by mgood** [comment]
I've added more info to the README documenting how to read and write comments. I don't think I'll add a special data-structure for working with properties including comments, but I've added a simple example in the README for how to make substitutions while writing the file in a way that will preserve comments.
